# RGB widget general settings
CONFIG_RGBLED_WIDGET_INTERVAL_MS=500

# RGB widget battery settings
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_ONLY_PERIPHERALS=y
CONFIG_RGBLED_WIDGET_BATTERY_BLINK_MS=1000
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_HIGH=2
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MEDIUM=3
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_LOW=1
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_CRITICAL=1
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MISSING=5

# RGB widget BT connection settings
CONFIG_RGBLED_WIDGET_CONN_BLINK_MS=1000
CONFIG_RGBLED_WIDGET_CONN_COLOR_CONNECTED=7
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=4
CONFIG_RGBLED_WIDGET_CONN_COLOR_DISCONNECTED=6

# RGB widget layer settings
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=4
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=5
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=7
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=1
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=1
CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=0
